### ISSUE TITLE
Filter cli shorthand

### ISSUE THREAD

**Issue by stoeffel** [studio-b12/doxie.filter#3]
It would be nice if I could do simple filtering without the need of a script.

i.e.

``` bash
$ dox | doxie --filter isPrivate true
# or maybe
$ dox | doxie --filter 'isPrivate=true'
```

**Comment by tomek-he-him** [comment]
Yup, definitely! I’ve been thinking of two higher-level plugins for this: `--drop` and `--keep`. They can even  use `--filter` under the hood.

Here’s a little demo: https://github.com/studio-b12/doxie.output/tree/eee2c7#cli-usage

**Comment by stoeffel** [comment]
> Here’s a little demo

nice!

**Comment by tomek-he-him** [comment]
And here the programmatic API: https://github.com/studio-b12/doxie.output/tree/eee2c7#programmatic-usage. Not so nice, but explicit.

I want it to be possible to do `--drop @api private` and `drop({'@api': 'private'})`.

**Comment by tomek-he-him** [comment]
Closing this then. It’s still here for reference.

Thanks for the input!

**Comment by tomek-he-him** [comment]
Oh and @stoeffel if you have other ideas to make the overall API simpler, I’m definitely open.

At the moment that’s my greatest concern. I wonder if the tool isn’t too flexible and therefore bloated.

**Comment by tomek-he-him** [comment]
My idea for this is to have low-level plugins like this one and `--render` – and high-level ones like `--keep` and `--preset`.
